### ISSUE TITLE
Manual writing boolean values

### ISSUE THREAD

**Issue by scoreboardxdev** [r4gus/zbor#21]
Hello, could you guide me on how to manually write boolean values? I assume I should do this using the writeSimple function, but I don't see any examples of that function being used in the documentation. Thanks!

**Comment by r4gus** [comment]
Hi, I've added two functions `writeTrue` and `writeFalse`.

**Comment by scoreboardxdev** [comment]
Thank you. What about writing floats?

**Comment by r4gus** [comment]
Added `writeFloat` as well as getters for `DataItem` (see release notes 0.15.2)

**Comment by r4gus** [comment]
I'll close this issue. @scoreboardxdev if you have further questions just open another issue.
