### ISSUE TITLE
zbor.stringify writes buffer instead of string

### ISSUE THREAD

**Issue by mbaracz** [r4gus/zbor#23]
Hello, I encountered an issue with serialization.

When I serialize a struct with a string field using zbor.stringify and then parse it using cbor-x, I get a Uint8Array instead of a string. I tried to resolve this by setting the field's serialization_type to .TextString, but the result is the same.

While manually serializing it solves the problem, it is not an ideal solution to serialize many structs by writing fields by hand.

I would appreciate it if you could look into this issue.

**Comment by r4gus** [comment]
Could you please provide the code you used to serialize the struct.

**Comment by mbaracz** [comment]
```zig
const std = @import("std");
const zbor = @import("zbor");

const S = struct {
    str: []const u8
};

test {
    const s = S { .str = "test" };

    var writer1 = std.ArrayList(u8).init(std.testing.allocator);
    defer writer1.deinit();

    // returns { str: Uint8Array(4) [ 116, 101, 115, 116 ] } when decoded
    try zbor.stringify(s, .{
        .field_settings = &.{
            .{ .name = "str", .field_options = .{ .serialization_type = .TextString } }
        }
    }, writer1.writer());

    var writer2 = std.ArrayList(u8).init(std.testing.allocator);
    defer writer2.deinit();

    // returns { str: 'test' } when decoded
    try zbor.build.writeMap(writer2.writer(), 1);
    try zbor.build.writeTextString(writer2.writer(), "str");
    try zbor.build.writeTextString(writer2.writer(), s.str);
}
```

**Comment by r4gus** [comment]
Replacing `field_options` with `value_options` should fix it.
